name: koompi_hotspot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.14.0+76

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_settings: ^4.1.0
  badges: ^2.0.1
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.3
  dart_ping: ^6.1.2
  date_format: ^2.0.2
  dio: ^4.0.4
  dropdown_button2: ^1.2.2
  easy_localization: ^3.0.0
  expansion_tile_card: ^2.0.0
  file_picker: ^4.4.0
  firebase_dynamic_links: ^2.0.6
  firebase_remote_config: ^2.0.0
  flare_flutter: ^3.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.0
  flutter_hooks: ^0.18.1
  flutter_image_compress: ^1.0.0
  flutter_inappwebview: ^5.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.0
  flutter_material_pickers: ^3.1.0
  flutter_slider_drawer: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  geolocator: ^8.2.0
  google_fonts: ^2.3.1
  google_nav_bar: ^5.0.5
  groovin_widgets: ^3.0.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.4+10
  in_app_update: ^3.0.0
  internet_connection_checker: ^0.0.1+3
  internet_speed_test: ^1.5.0
  intl_phone_number_input: ^0.7.0+2
  intro_slider: ^3.0.3
  jwt_decoder: ^2.0.1
  latlong2: ^0.8.0
  line_awesome_icons: ^1.0.4+2
  line_icons: ^2.0.1
  linkable: ^3.0.1
  location: ^4.3.0
  onesignal_flutter: ^3.2.8
  package_info: ^2.0.2
  page_transition: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  percent_indicator: ^4.0.0
  permission_handler: ^9.0.1
  pin_code_fields: ^7.2.0
  provider: ^6.0.2
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  quick_actions: ^0.6.0+2
  responsive_framework: ^0.1.2
  rflutter_alert: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sliding_sheet: ^0.5.2
  syncfusion_flutter_gauges: ^19.1.69
  url_launcher: ^6.0.6
  webview_flutter: ^3.0.1
  wifi_connector: ^2.0.0
  wifi_iot: ^0.3.15

flutter_icons:
  image_path: "assets/images/Koompi-WiFi-Icon.png"
  ios: true
  android: true

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/animations/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
